baseURL = "LEMarshall.github.io/"
title = "TestBlog"
theme = "hugo-theme-blueberry-detox"
[params]
	description = "Blogging on IT topics and more"
	author = "Laurent Marshall"
	copyright = "Copyright (c) 2015, Laurent Marshall; all rights reserved."
