baseurl = "http://104.155.49.77"
title = "TestBlog"
author = "Laurent Marshall"
copyright = "Copyright (c) 2015, Laurent Marshall; all rights reserved."
[params]
	sidbartitle = "TestBlog"
	sidebartagline = "This is a test"

